# Generated by Django 4.1.3 on 2023-11-06 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('veg_or_nonveg', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], max_length=10)),
                ('no_of_chefs', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
