# Generated by Django 4.1.3 on 2023-11-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='veg_or_nonveg',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Both', 'Non-Vegetarian')], max_length=255),
        ),
    ]
