# Generated by Django 4.2.7 on 2023-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_veg_or_nonveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
