# Generated by Django 4.2.7 on 2023-11-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]