# Generated by Django 4.2.7 on 2023-11-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_notification_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='restaurant',
        ),
    ]
