# Generated by Django 4.2.7 on 2023-12-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_notification_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
