# Generated by Django 4.2.7 on 2023-12-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
