# Generated by Django 4.2.7 on 2023-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profilePicture'),
        ),
    ]
