# Generated by Django 4.2.7 on 2023-12-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_profile_address_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profilePicture/'),
        ),
    ]
