# Generated by Django 4.2.7 on 2023-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
