# Generated by Django 4.2.7 on 2023-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cuisine',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
