# Generated by Django 4.2.7 on 2023-12-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuModel', to='menu.menu'),
        ),
    ]
