# Generated by Django 4.2.7 on 2023-12-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_review_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
