# Generated by Django 4.2.7 on 2023-11-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_order_date_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash on delivery', 'Cash on delivery'), ('Net banking', 'Net banking'), ('UPI', 'UPI')], max_length=255, null=True),
        ),
    ]
