# Generated by Django 4.2.7 on 2023-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_total_bill_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
