# Generated by Django 4.2.7 on 2023-12-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_primary'),
        ('order', '0007_alter_order_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
    ]
